import { beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ refreshSession: vi.fn(), insert: vi.fn(), select: vi.fn(), single: vi.fn() }))
vi.mock('./supabase', () => ({ supabase: { auth: { refreshSession: mocks.refreshSession }, from: vi.fn(() => ({ insert: mocks.insert })) } }))
import { analyzeNoticing, saveEditorialRevision } from './choko-ai'
const generation = { id: 'g-1', generation_group_id: 'group-1', noticing_id: 'n-1', user_id: 'u-1', generation_type: 'caption' as const, model_provider: 'openai', model_name: 'test-model', prompt_version: 'choko-vision-v1', input_snapshot: {}, generated_text: 'The untouched AI proposal remains here.', structured_output: {} as never, confidence: .8, uncertainties: [], created_at: '2026-08-07' }
describe('Choko AI client persistence', () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.refreshSession.mockResolvedValue({ data: { session: { access_token: 'fresh-token' } }, error: null }); mocks.insert.mockReturnValue({ select: mocks.select }); mocks.select.mockReturnValue({ single: mocks.single }); mocks.single.mockResolvedValue({ data: { id: 'r-1', final_human_text: 'A quieter human version.' }, error: null }) })
  it('refreshes the login token immediately before analysis', async () => { vi.stubGlobal('fetch', vi.fn(async () => ({ ok: true, json: async () => ({ generations: [generation] }) }))); await analyzeNoticing('00000000-0000-4000-8000-000000000001'); expect(mocks.refreshSession).toHaveBeenCalledOnce(); expect(fetch).toHaveBeenCalledWith('/api/choko-analyze', expect.objectContaining({ headers: expect.objectContaining({ Authorization: 'Bearer fresh-token' }) })) })
  it('surfaces an AI endpoint failure without fabricating content', async () => { vi.stubGlobal('fetch', vi.fn(async () => ({ ok: false, json: async () => ({ error: 'Provider unavailable' }) }))); await expect(analyzeNoticing('00000000-0000-4000-8000-000000000001')).rejects.toThrow('Provider unavailable') })
  it('keeps the AI proposal while persisting human text and feedback reason', async () => { await saveEditorialRevision({ noticingId: 'n-1', userId: 'u-1', generation, finalText: 'A quieter human version.', decision: 'edited', feedbackReason: 'The image is quiet, so the caption should say less.', feedbackCategories: ['too_poetic'] }); expect(mocks.insert).toHaveBeenCalledWith(expect.objectContaining({ original_ai_text: generation.generated_text, final_human_text: 'A quieter human version.', feedback_reason: 'The image is quiet, so the caption should say less.', feedback_categories: ['too_poetic'] })) })
  it('persists an accepted human caption as a revision', async () => { await saveEditorialRevision({ noticingId: 'n-1', userId: 'u-1', generation, finalText: generation.generated_text, decision: 'accepted' }); expect(mocks.insert).toHaveBeenCalledWith(expect.objectContaining({ decision: 'accepted', final_human_text: generation.generated_text })) })
})
