import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowLeft, ImagePlus, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { VoiceRecorder } from '../components/VoiceRecorder'
import { useAuth } from '../AuthContext'
import { createNoticing, getNoticing, updateNoticing } from '../lib/noticings'
import { noticingSchema, validateFiles } from '../lib/validation'
import type { NoticingInput } from '../types'

export function NoticingFormPage() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate(); const { session } = useAuth(); const [files, setFiles] = useState<File[]>([]); const [fileError, setFileError] = useState(''); const [submitError, setSubmitError] = useState(''); const [tagText, setTagText] = useState(''); const [saving, setSaving] = useState(false)
  const { register, handleSubmit, reset, setValue, formState: { errors } } = useForm<NoticingInput>({ resolver: zodResolver(noticingSchema), defaultValues: { observation_text: '', status: 'unreviewed', tags: [] } })
  useEffect(() => { if (id) getNoticing(id).then((item) => { const tags = item.tags?.map((t) => t.name) ?? []; setTagText(tags.join(', ')); reset({ title: item.title ?? '', observation_text: item.observation_text ?? '', location_name: item.location_name ?? '', captured_at: item.captured_at?.slice(0, 16) ?? '', weather: item.weather ?? '', time_of_day: item.time_of_day ?? '', light_condition: item.light_condition ?? '', environment_type: item.environment_type ?? '', mood: item.mood ?? '', status: item.status, tags }) }) }, [id, reset])
  const previews = useMemo(() => files.map((file) => ({ file, url: URL.createObjectURL(file) })), [files])
  function choose(next: File[]) { const errors = validateFiles(next); setFileError(errors.join(' ')); if (!errors.length) setFiles(next) }
  async function submit(input: NoticingInput) { if (!editing && !files.some((f) => !f.type.startsWith('audio/'))) { setFileError('Add at least one image or video.'); return } if (!session?.user) return; setSaving(true); setSubmitError(''); try { const payload = { ...input, tags: tagText.split(',').map((x) => x.trim()).filter(Boolean) }; const nextId = id ? (await updateNoticing(id, payload, session.user), id) : await createNoticing(payload, files, session.user); sessionStorage.removeItem('choko-draft'); navigate(`/noticings/${nextId}`) } catch (e) { setSubmitError(e instanceof Error ? e.message : 'Could not save this noticing.') } finally { setSaving(false) } }
  return <div className="page form-page"><Link className="back" to={editing && id ? `/noticings/${id}` : '/library'}><ArrowLeft size={17}/> Back</Link><div className="page-title"><p className="kicker">{editing ? 'Keep the moment true' : 'A new small wonder'}</p><h1>{editing ? 'Edit noticing' : 'What made you stop?'}</h1><p>The observation is the heart of every noticing.</p></div><form onSubmit={handleSubmit(submit)}>
    {!editing && <section className="form-section"><div className="section-copy"><span>01</span><div><h2>Original moment</h2><p>Add up to 10 images or one video. Originals are always preserved.</p></div></div><label className="dropzone"><ImagePlus/><strong>Choose from your camera roll</strong><span>JPEG, PNG, WebP, HEIC, MP4 or MOV</span><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,video/mp4,video/quicktime" multiple onChange={(e) => choose(Array.from(e.target.files ?? []))}/></label>{fileError && <p className="error">{fileError}</p>}<div className="preview-row">{previews.map(({ file, url }, index) => <div className="preview" key={url}>{file.type.startsWith('video/') ? <video src={url}/> : <img src={url} alt=""/>}<button type="button" onClick={() => choose(files.filter((_, i) => i !== index))} aria-label={`Remove ${file.name}`}><X/></button>{index === 0 && <span>Primary</span>}</div>)}</div></section>}
    <section className="form-section"><div className="section-copy"><span>{editing ? '01' : '02'}</span><div><h2>Your observation</h2><p>Keep the first thought simple and honest.</p></div></div><label className="observation">Why did you stop?<textarea rows={5} autoFocus={!editing} placeholder="The spider web looked invisible until the sun touched it…" {...register('observation_text')} onChange={(e) => { register('observation_text').onChange(e); sessionStorage.setItem('choko-draft', e.target.value) }}/>{errors.observation_text && <small className="error">{errors.observation_text.message}</small>}</label>{!editing && <VoiceRecorder onChange={(file) => setFiles((current) => [...current.filter((f) => !f.type.startsWith('audio/')), ...(file ? [file] : [])])}/>}</section>
    <section className="form-section"><div className="section-copy"><span>{editing ? '02' : '03'}</span><div><h2>Context</h2><p>Optional details make moments easier to rediscover.</p></div></div><div className="form-grid"><label>Title<input {...register('title')} placeholder="Morning web"/></label><label>Captured at<input type="datetime-local" {...register('captured_at')}/></label><label>Place<input {...register('location_name')} placeholder="The lower meadow"/></label><label>Time of day<input {...register('time_of_day')} placeholder="Early morning"/></label><label>Light<input {...register('light_condition')} placeholder="Soft backlight"/></label><label>Weather<input {...register('weather')} placeholder="Misty"/></label><label>Environment<input {...register('environment_type')} placeholder="Meadow"/></label><label>Mood<input {...register('mood')} placeholder="Quiet wonder"/></label><label className="wide">Tags<input value={tagText} onChange={(e) => { setTagText(e.target.value); setValue('tags', e.target.value.split(',').filter(Boolean)) }} placeholder="mist, spider-web, sunrise"/><small>Separate tags with commas.</small></label><label>Status<select {...register('status')}><option value="draft">Draft</option><option value="unreviewed">Unreviewed</option><option value="reviewed">Reviewed</option><option value="ready">Ready</option><option value="archived">Archived</option></select></label></div></section>{submitError && <p className="error">{submitError}</p>}<div className="form-actions"><Link className="secondary" to="/library">Cancel</Link><button className="primary" disabled={saving}>{saving ? 'Keeping it safe…' : editing ? 'Save changes' : 'Save noticing'}</button></div></form></div>
}
